// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2129.robot;

import edu.wpi.first.wpilibj.CameraServer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController tankDriveLeftDriveController;
    public static SpeedController tankDriveRightDriveController;
    public static RobotDrive tankDriveRobotDrive;
    public static SpeedController shooterLeftWheel;
    public static SpeedController shooterRightWheel;
    public static SpeedController shooterBallProd;
    public static SpeedController shooterElevator;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static SpeedController shooterElevatorBoost;
    
	public static CameraServer server;
	
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        tankDriveLeftDriveController = new Talon(0);
        LiveWindow.addActuator("TankDrive", "LeftDriveController", (Talon) tankDriveLeftDriveController);
        
        tankDriveRightDriveController = new Talon(1);
        LiveWindow.addActuator("TankDrive", "RightDriveController", (Talon) tankDriveRightDriveController);
        
        tankDriveRobotDrive = new RobotDrive(tankDriveLeftDriveController, tankDriveRightDriveController);
        
        tankDriveRobotDrive.setSafetyEnabled(true);
        tankDriveRobotDrive.setExpiration(0.1);
        tankDriveRobotDrive.setSensitivity(0.5);
        tankDriveRobotDrive.setMaxOutput(1.0);

        tankDriveRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        shooterLeftWheel = new Talon(2);
        LiveWindow.addActuator("Shooter", "LeftWheel", (Talon) shooterLeftWheel);
        
        shooterRightWheel = new Talon(3);
        LiveWindow.addActuator("Shooter", "RightWheel", (Talon) shooterRightWheel);
        
        shooterBallProd = new Talon(4);
        LiveWindow.addActuator("Shooter", "BallProd", (Talon) shooterBallProd);
        
        shooterElevator = new Talon(2);
        LiveWindow.addActuator("Shooter", "Elevation", (Talon) shooterElevator);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        shooterElevatorBoost = new Talon(3);
        
        server = CameraServer.getInstance();
        server.setQuality(50);
        server.startAutomaticCapture("cam0");
    }
}
